name: senada
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.4
  email_validator: ^3.0.0
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/Bank_Logo/
    - assets/images/E_Wallet/
