// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIC4IXhA4Cg0xbAehNPnhBGIExOfXFg4',
    appId: '1:575637237417:web:0e836f6140732158f183b8',
    messagingSenderId: '575637237417',
    projectId: 'tb-senada',
    authDomain: 'tb-senada.firebaseapp.com',
    storageBucket: 'tb-senada.firebasestorage.app',
    measurementId: 'G-29VL3YXL92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonXAXFnB-mDdYHZ3VlG9tJVxVxqT2VaU',
    appId: '1:575637237417:android:da1651d0ed287714f183b8',
    messagingSenderId: '575637237417',
    projectId: 'tb-senada',
    storageBucket: 'tb-senada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLC_IWSpWZgC8bIOVuxxQZS7yvyuxUmJ0',
    appId: '1:575637237417:ios:e649db7d0844df77f183b8',
    messagingSenderId: '575637237417',
    projectId: 'tb-senada',
    storageBucket: 'tb-senada.firebasestorage.app',
    iosBundleId: 'kel7.senada.senada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLC_IWSpWZgC8bIOVuxxQZS7yvyuxUmJ0',
    appId: '1:575637237417:ios:e649db7d0844df77f183b8',
    messagingSenderId: '575637237417',
    projectId: 'tb-senada',
    storageBucket: 'tb-senada.firebasestorage.app',
    iosBundleId: 'kel7.senada.senada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADIC4IXhA4Cg0xbAehNPnhBGIExOfXFg4',
    appId: '1:575637237417:web:dc9f8e38fed90639f183b8',
    messagingSenderId: '575637237417',
    projectId: 'tb-senada',
    authDomain: 'tb-senada.firebaseapp.com',
    storageBucket: 'tb-senada.firebasestorage.app',
    measurementId: 'G-575V29HSW0',
  );

}